kos/kosstore/Models/Script.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kosstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Script
    {
        public Script()
        {
            this.ScriptComments = new HashSet<ScriptComment>();
            this.Likes = new HashSet<Like>();
        }
    
        public int ID { get; set; }
        public string ScriptName { get; set; }
        public string Script1 { get; set; }
        public int UserId { get; set; }
        public System.DateTime Submitted { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual UserProfileEF UserProfile { get; set; }
        public virtual ICollection<ScriptComment> ScriptComments { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual ScriptCategory ScriptCategory { get; set; }
    }
}

kos/kosstore/Controllers/ScriptController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kosstore.Models;
using kosstore.Filters;
using WebMatrix.WebData;

namespace kosstore.Controllers
{
    [InitializeSimpleMembership]
    public class ScriptController : Controller
    {
        private kosEntities db = new kosEntities();

        /// <summary>
        /// View Index -- ie, a list of all scripts
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(int category = 0)
        {
            if (category > 0)
            {
                return View(db.Scripts.Where(m => m.ScriptCategory.ID == category).OrderBy(m => m.Submitted).ToList());
            }
            else
            {
                return View(db.Scripts.ToList());
            }
        }

        /// <summary>
        /// Adds a comment to a script
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Comment(ScriptCommentModel model)
        {
            ScriptComment comment = new ScriptComment();
            comment.Added = DateTime.Now;
            comment.Comment = Helpers.StripTagsCharArray(model.comment);
            comment.ScriptId = model.onScipt;
            comment.UserId = WebSecurity.CurrentUserId;

            db.ScriptComments.Add(comment);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = model.onScipt });
        }

        /// <summary>
        /// View the details of the script
        /// </summary>
        /// <param name="id">The id of the script to view</param>
        /// <returns></returns>
        public ActionResult Details(int id = 0)
        {
            Script script = db.Scripts.Find(id);
            if (script == null)
            {
                return HttpNotFound();
            }
            script.Script1 = script.Script1.Replace("\n", "<br>");
            return View(script);
        }

        /// <summary>
        /// View an empty script create page
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Postback for the create page
        /// </summary>
        /// <param name="script"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Script script)
        {
            if (ModelState.IsValid)
            {
                script.UserId = WebSecurity.CurrentUserId;
                script.ScriptCategory.ID = 1;
                db.Scripts.Add(script);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(script);
        }

        /// <summary>
        /// View and edit a script
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            Script script = db.Scripts.Find(id);
            if (script == null)
            {
                return HttpNotFound();
            }

            if (script.UserId != WebSecurity.CurrentUserId) return HttpNotFound();

            return View(script);
        }

        /// <summary>
        /// Post back for the edit page
        /// </summary>
        /// <param name="script"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Script script)
        {
            if (ModelState.IsValid && script.UserId == WebSecurity.CurrentUserId)
            {
                //script.Script1 = Helpers.StripTagsCharArray(script.Script1);
                //script.Script1 = System.Net.WebUtility.HtmlEncode(script.Script1);'

                script.Submitted = DateTime.Now;

                db.Entry(script).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(script);
        }

        /// <summary>
        /// Delete a script
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Script script = db.Scripts.Find(id);
            if (script == null)
            {
                return HttpNotFound();
            }

            if (script.UserId != WebSecurity.CurrentUserId) return HttpNotFound();

            return View(script);
        }

        /// <summary>
        /// Post back for the delete page
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Script script = db.Scripts.Find(id);
            if (script.UserId != WebSecurity.CurrentUserId) return HttpNotFound();
            db.Scripts.Remove(script);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Destroy this controller
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

kos/kosstore/Views/Script/Create.cshtml
@model kosstore.Models.Script

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Script</legend>

        <div class="editor-label">
            @Html.Label("Script Name")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ScriptName)
            @Html.ValidationMessageFor(model => model.ScriptName)
        </div>

        <div class="editor-label">
            @Html.Label("Enter Script here")
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Script1)
            @Html.ValidationMessageFor(model => model.Script1)
        </div>

        <p>
            <input type="submit" value="Create" onclick="doEncode()" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        function doEncode() {
            f = $("#Script1").get(0);
            f.value = htmlEncode(f.value);
            return true;
        }

        function htmlEncode(str) {
            // This must be done in a proper order to achive desired results.
            str = this.replaceAll(str, "&", "&amp;");
            str = this.replaceAll(str, "<", "&lt;");
            str = this.replaceAll(str, ">", "&gt;");
            str = this.replaceAll(str, " ", "&nbsp;");
            return str;
        }


        function replaceAll(str, subStr, newStr) {
            var offset = 0;
            var index = str.indexOf(subStr);
            while (index != -1) {
                str = str.substr(0, index) + newStr + str.substr(index + subStr.length);
                offset = index + newStr.length;
                index = str.indexOf(subStr, offset);
            }
            return str;
        }
    </script>
}

kos/kosstore/Views/Script/Delete.cshtml
@model kosstore.Models.Script

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Script</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ScriptName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ScriptName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Script1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Script1)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

kos/kosstore/Views/Script/Details.cshtml
@model kosstore.Models.Script

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Script</legend>

    <div class="display-label">
        @Html.DisplayName("Script Name")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ScriptName)
    </div>

    <div class="display-label">
        @Html.DisplayName("The Script")
    </div>
    <div class="display-field" id="script">
        @Html.Raw(Model.Script1)
    </div>

    <div class="display-label">
        @Html.DisplayName("Created By")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>
</fieldset>

@foreach (var item in Model.ScriptComments)
{
    <div class="scriptComment">
        <div class="commentBy">@Html.DisplayFor(m => item.UserProfile.UserName)</div>
        <div class="commentOn">@Html.DisplayFor(m => item.Added)</div>
        <div class="comment">@Html.DisplayFor(m => item.Comment)</div>
    </div>
}

@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("Comment", "Script", FormMethod.Post))
    {
    <p>
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        @Html.Hidden("onScipt", Model.ID)

        @Html.Label("Comment")
        @Html.TextArea("comment");
    </p>
    <p>
        <input type="submit" value="Comment" />
    </p>
    }
}

<p>
    @if (Request.IsAuthenticated)
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) @Html.Encode(" | ")
    }
    @Html.ActionLink("Back to List", "Index")
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        function doEncode() {
            f = $("#Script1").get(0);
            f.value = htmlEncode(f.value);
            return true;
        }

        function htmlEncode(str) {
            // This must be done in a proper order to achive desired results.
            str = this.replaceAll(str, "&", "&amp;");
            str = this.replaceAll(str, "<", "&lt;");
            str = this.replaceAll(str, ">", "&gt;");
            str = this.replaceAll(str, " ", "&nbsp;");
            return str;
        }

        function htmlDecode() {
            str = $("#script").get(0).innerText;
            str = this.replaceAll(str, "&nbsp;", " ");
            str = this.replaceAll(str, "&gt;", ">");
            str = this.replaceAll(str, "&lt;", "<");
            str = this.replaceAll(str, "&amp;", "&");
            $("#script").get(0).innerText = str;
        }

        $(function () {
            htmlDecode();
        });

        function replaceAll(str, subStr, newStr) {
            var offset = 0;
            var index = str.indexOf(subStr);
            while (index != -1) {
                str = str.substr(0, index) + newStr + str.substr(index + subStr.length);
                offset = index + newStr.length;
                index = str.indexOf(subStr, offset);
            }
            return str;
        }
    </script>
}

kos/kosstore/Views/Script/Edit.cshtml
@model kosstore.Models.Script

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Script</legend>

        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.UserId)

        <div class="editor-label">
            @Html.Label("Script Name")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ScriptName)
            @Html.ValidationMessageFor(model => model.ScriptName)
        </div>

        <div class="editor-label">
            @Html.Label("Script")
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Script1)
            @Html.ValidationMessageFor(model => model.Script1)
        </div>

        <div class="editor-label">
            @Html.Label("Category")
        </div>

        <div class="editor-field">
            <select name="category">
                @{
    kosstore.Models.kosEntities db = new kosstore.Models.kosEntities();
    var cats = db.ScriptCategories.Where(m => m.ParentCategory != null).ToList();
    foreach (var cat in cats)
    {
        @Html.Raw("<option value='" + cat.ID + "'" + (cat.ID == Model.Category ? " selected=true" : "") + ">" + db.ScriptCategories.Find(cat.ParentCategory).CategoryName + " : " + cat.CategoryName + "</option>");
    }
                }
            </select>
        </div>

        <p>
            <input type="submit" value="Save" onclick="doEncode()" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        function doEncode() {
            f = $("#Script1").get(0);
            f.value = htmlEncode(f.value);
            return true;
        }

        function htmlEncode(str) {
            // This must be done in a proper order to achive desired results.
            str = this.replaceAll(str, "&", "&amp;");
            str = this.replaceAll(str, "<", "&lt;");
            str = this.replaceAll(str, ">", "&gt;");
            str = this.replaceAll(str, " ", "&nbsp;");
            return str;
        }

        function htmlDecode() {
            str = $("#Script1").get(0).value;
            str = this.replaceAll(str, "&nbsp;", " ");
            str = this.replaceAll(str, "&gt;", ">");
            str = this.replaceAll(str, "&lt;", "<");
            str = this.replaceAll(str, "&amp;", "&");
            $("#Script1").get(0).value = str;
        }

        $(function () { htmlDecode(); });

        function replaceAll(str, subStr, newStr) {
            var offset = 0;
            var index = str.indexOf(subStr);
            while (index != -1) {
                str = str.substr(0, index) + newStr + str.substr(index + subStr.length);
                offset = index + newStr.length;
                index = str.indexOf(subStr, offset);
            }
            return str;
        }
    </script>
}

kos/kosstore/Views/Script/Index.cshtml
@model IEnumerable<kosstore.Models.Script>

@{
    ViewBag.Title = "kOS Script Directory";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            <a>@Html.DisplayName("Script Name")</a>
        </th>
        <th>
            @Html.DisplayName("Created by")
        </th>
        <th class="desc">
            <a>@Html.DisplayName("Submitted")</a>
        </th>
        <th>
            @Html.DisplayName("Category")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ScriptName)
            </td>
            <td>
                @Html.DisplayFor(m => item.UserProfile.UserName)
            </td>
            <td>
                @Html.DisplayFor(m => item.Submitted)
            </td>
            <td>
                @Html.DisplayFor(m => item.ScriptCategory.CategoryName)
            </td>
            <td>
                @if ((int)WebSecurity.CurrentUserId == item.UserId)
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) @Html.Encode(" | ")
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }) @Html.Encode(" | ")
                }
            @Html.ActionLink("Details", "Details", new { id = item.ID })
            </td>
        </tr>
    }

</table>